config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
post '/tweets/;id/done' => 'tweets#done', as: 'done'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @today = Date.today
    @tweet = Tweet.new
    @tweets = Tweet.where(done_at:nill).order(:time)
    @tweets_done = Tweet.where.not(done_at:nill)
  end
  
  def create
    tweet = Tweet.new(tweet_params)
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  
  def done
    @today = Date.today
    tweet = Tweet.find(params[:id])
    tweet.update(done_at: @today)
    redirect_to :action => "index"
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:time,:title,:done_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<%= form_for @tweet do |f| %>
    <%= f.label :タスク名 %>
    <%= f.text_field :title, :size => 40 %></br>
    <%= f.label :締切 %>
    <%= f.date_field :time, :size => 140 %>
<%= f.submit "tweetする" %>
<% end %>

<div class="tweet-container"%>
  <div class="item"%>
    <h1>タスク一覧</h1>
    <% @tweets.each do |t| %>
      <div class="tweet">
      <%if (t.time - @today).to_i > -1 %>
        タスク名:<b><%= t.title %></b></br>
        締切:<%= t.time %></br>
        残り:<%= t.time - @today).to_i %>日</br>
        <%= button_to 'Done', done_path(t.id), method: :post %></br></br>
    <% else %>
      <b><%= t.title %></b></br>
      締切:<%= t.time %>
      <%= (t.time - @today).to_i * -1 %>日期限が経過しています😊</br>
      <%= button_to 'Done', done_path(t.id), method: :post %></br></br>
    <% end %>
    </div>
  <% end %>
</div>
<div class="item"%>
<h1>完了したタスク</h1>
    <% @tweets?done.each do |t| %>
     <div class="tweet">
       タスク名:<b><%= t.title %></b></br>
       完了日:<%= t.done_at.strftime('%Y-%m-%d') %></br></br>
    </div>
    <% end %>
</div>
</div>